package connectrpc

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"

	"connectrpc.com/connect"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	auth "github.com/alexey-petrov/go-server/authService"
	authv1 "github.com/alexey-petrov/go-server/gen/auth/v1"        // generated by protoc-gen-go
	"github.com/alexey-petrov/go-server/gen/auth/v1/authv1connect" // generated by protoc-gen-connect-go
	"github.com/alexey-petrov/go-server/keys"
)

type AuthServer struct{}

func (s *AuthServer) Login(
	ctx context.Context,
	req *connect.Request[authv1.LoginRequest],
) (*connect.Response[authv1.LoginResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&authv1.LoginResponse{
		AccessToken: fmt.Sprintf("Hello, %s!", req.Msg.Email),
	})
	res.Header().Set("Login-Version", "v1")
	return res, nil
}

// Implement the ServeHTTP method to satisfy http.Handler interface
func ServeHTTP(w http.ResponseWriter, r *http.Request) {
	// req, ok := getHttpRequestFromContext(r.Context())
	// fmt.Println("HELLO>", req, ok)

}

func NewAuthInterceptor() connect.UnaryInterceptorFunc {
	interceptor := func(next connect.UnaryFunc) connect.UnaryFunc {
		return connect.UnaryFunc(func(
			ctx context.Context,
			req connect.AnyRequest,
		) (connect.AnyResponse, error) {

			return next(ctx, req)
		})
	}
	return connect.UnaryInterceptorFunc(interceptor)
}

func ConnectRPC() {
	publicUrl := os.Getenv("PUBLIC_URL")

	auth := &auth.AuthServiceServer{}
	mux := http.NewServeMux()
	interceptors := connect.WithInterceptors(NewAuthInterceptor())
	path, handler := authv1connect.NewAuthServiceHandler(auth, interceptors)
	fmt.Println(publicUrl)
	corsHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if publicUrl != "" {
			w.Header().Set("Access-Control-Allow-Origin", publicUrl)

		} else {
			w.Header().Set("Access-Control-Allow-Origin", "http://localhost:3000")
		}
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization, Set-Cookie, connect-protocol-version")
		w.Header().Set("Access-Control-Allow-Credentials", "true")

		ctx := context.WithValue(r.Context(), keys.HttpRequestKey, keys.HttpRequestResponse{Request: r, Response: w})
		// Call the next handler with the updated context
		handler.ServeHTTP(w, r.WithContext(ctx))
	})
	fmt.Println("ConnectRPC is serving at :8080")
	mux.Handle(path, corsHandler)

	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)

}
